<?php
session_start();
require_once('../tcpdf/tcpdf.php');
 include('../queries.php');
 require '../config.php';
// create new PDF document

$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor($_SESSION["user"]);
$pdf->SetTitle('Home Exchange Report');
$pdf->SetSubject('Report');
$pdf->SetKeywords('PDF, Report, export');

// set default header data
$pdf->SetHeaderData("", PDF_HEADER_LOGO_WIDTH, "Report","Generated By: ".$_SESSION["user"]);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font
$pdf->SetFont('helvetica', '', 10);

// add a page
$pdf->AddPage();
$date = date( 'l, F d, Y ', time());
$month_sign_ups = mysqli_fetch_array($signupsMonth);
$week_1_signups = mysqli_fetch_array($signupsWk1);
$week_2_signups = mysqli_fetch_array($signupsWk2);
$week_3_signups = mysqli_fetch_array($signupsWk3);
$week_4_signups = mysqli_fetch_array($signupsWk4);
$month_new_homeowners = mysqli_fetch_array($newHomeOwnersMonth);
$week_1_homeowners = mysqli_fetch_array($newHomeOwnersWk1);
$week_2_homeowners = mysqli_fetch_array($newHomeOwnersWk2);
$week_3_homeowners = mysqli_fetch_array($newHomeOwnersWk3);
$week_4_homeowners = mysqli_fetch_array($newHomeOwnersWk4);
$week1_home_regs = mysqli_fetch_array($newHomesWk1);
$week2_home_regs = mysqli_fetch_array($newHomesWk2);
$week3_home_regs = mysqli_fetch_array($newHomesWk3);
$week4_home_regs = mysqli_fetch_array($newHomesWk4);
$tier1_no = mysqli_fetch_array($tier1number);
$tier2_no = mysqli_fetch_array($tier2number);
$tier3_no = mysqli_fetch_array($tier3number);
$tier4_no = mysqli_fetch_array($tier4number);
$tier5_no = mysqli_fetch_array($tier5number);
$total_Home_Owners = mysqli_fetch_array($totalHomeOwners);
$total_home_availabilities = mysqli_fetch_array($totalAvailabilitiesMonth);
$week_1_availabilities = mysqli_fetch_array($availabilitiesWk1);
$week_2_availabilities = mysqli_fetch_array($availabilitiesWk2);
$week_3_availabilities = mysqli_fetch_array($availabilitiesWk3);
$week_4_availabilities = mysqli_fetch_array($availabilitiesWk4);
$month_requests_no = mysqli_fetch_array($newRequestsMonth);
$week_1_requests = mysqli_fetch_array($requestsWk1);
$week_2_requests = mysqli_fetch_array($requestsWk2);
$week_3_requests = mysqli_fetch_array($requestsWk3);
$week_4_requests = mysqli_fetch_array($requestsWk4);
$week_1_exchanges = mysqli_fetch_array($exchangesWk1);
$week_2_exchanges = mysqli_fetch_array($exchangesWk2);
$week_3_exchanges = mysqli_fetch_array($exchangesWk3);
$week_4_exchanges = mysqli_fetch_array($exchangesWk4);
$exchanges_month = mysqli_fetch_array($exchangesMonth4);



$html = '<h1 style="text-align:center"><strong><img src="../assets/images/lOGO.png" height="100" width="150"></strong></h1>
<b>Date: '.$date.'</b><br>
<h3>Introduction</h3>
    <p>
      This Company Performance Report (CPR) has been designed to assist 
      in evaluating the companys current performance relative to previous periods. The comparative ratios and statistics contained on the following pages
      represent broad performance "yardsticks" against which the companys
      operating results can be measured.
    </p>
    <h2>Performance Analysis</h2>
<p>Below is the report that examines the company performance for the last one month.</p>
<p>This month we managed to get<b> '.$month_sign_ups['sum'].' new sign ups</b> on the platform. This reflects the interest of people in Home Swap as their holiday solution. The <b>weekly sign up comparison</b> this month is as follows:</p>
<ul>
    <b><li>Week 1: '.$week_1_signups['sum'].' customers</li>
    <li>Week 2: '.$week_2_signups['sum'].' customers</li>
    <li>Week 3: '.$week_3_signups['sum'].' customers</li>
    <li>Week 4: '.$week_4_signups['sum'].' customers</li></b>
</ul>
<p>There is currently a total of <b>'.$activeCustomersCount.' active customers</b> on the platform and <b>'.$blacklistedCount.' blacklisted customers</b>. Of the registered customers, there currently are <b> '.mysqli_num_rows($subscribersList).' newsletter subscribers</b> which is <b>'.number_format((float)(mysqli_num_rows($subscribersList)/$month_sign_ups['sum']) * 100,2,'.','').'%'.' of the active customers</b> </p>
<p>There were <b>'.$month_new_homeowners['sum'].' new home owners</b> in the previous month. This makes the <b>total home owners '.$total_Home_Owners['sum'].'</b> which is  <i>'.number_format((float)(mysqli_num_rows($totalHomeOwners)/$activeCustomersCount) * 100,2,'.','').'% of the total registered customers</i>. The weekly uptake of home owners is as follows:</p>
<ol>
    <b><li>Week 1: '.$week_1_homeowners['sum'].' home owners</li>
    <li>Week 2: '.$week_2_homeowners['sum'].' home owners</li>
    <li>Week 3: '.$week_3_homeowners['sum'].' home owners</li>
    <li>Week 4: '.$week_4_homeowners['sum'].' home owners</li></b>
</ol>
<p>We also managed to get <b>5 new homes</b> on the platform. The <b>weekly home registration comparison</b> is as follows:</p>
<ol>
    <b><li>Week 1: '.$week1_home_regs['sum'].' homes</li>
    <li>Week 2: '.$week2_home_regs['sum'].' homes</li>
    <li>Week 3: '.$week3_home_regs['sum'].' homes</li>
    <li>Week 4: '.$week4_home_regs['sum'].' homes</li></b>
</ol>
<p>There is currently a total of <b>'.$activeHomesCount.' active homes</b> on the platform and <b>'.$deactivatedHomesCount.' blacklisted homes</b>.</p>
<p>There is a total of 5 home tiers on the basis of facilities found in the homes. Given the new home uptake, below is the <b>home tier distribution at the moment</b>.</p>
<table border="1" cellspacing="1" cellpadding="4" align="center">
    <tr>
        <th></th>
        <th><b>Tier 1</b></th>
        <th><b>Tier 2</b></th>
        <th><b>Tier 3</b></th>
        <th><b>Tier 4</b></th>
        <th><b>Tier 5</b></th>   
    </tr>
    <tr>
        <td><b>Number of homes</b></td>
        <td>'.$tier1_no['sum'].'</td>
        <td>'.$tier2_no['sum'].'</td>
        <td>'.$tier3_no['sum'].'</td>
        <td>'.$tier4_no['sum'].'</td>
        <td>'.$tier5_no['sum'].'</td>
    </tr>
    <tr>
        <td><b>Percentage of total homes</b></td>
        <td>'.number_format((float)($tier1_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
        <td>'.number_format((float)($tier2_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
        <td>'.number_format((float)($tier3_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
        <td>'.number_format((float)($tier4_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
        <td>'.number_format((float)($tier5_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    </table>
<p>With that the <b>home features distribution</b> among the registered homes in Home Swap and their corresponding percentage of the total homes is as follows:</p>
<table border="1" cellspacing="1" cellpadding="4" align="center">
<tr>
    <th width="40%"><b>Feature</b></th>
    <th width="30%"><b>Number of homes</b></th>
    <th width="30%"><b>Percentage</b></th>     
</tr>
<tr>
  <td scope="row">Swimming Pool</td>
  <td>'.$swimming_no['sum'].'</td>
  <td>'.number_format((float)($swimming_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
</tr>
<tr>
      <th scope="row">Houses</th>
      <td>'.$houses_no['sum'].'</td>
      <td>'.number_format((float)($houses_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Apartments</th>
      <td>'.$apartments_no['sum'].'</td>
      <td>'.number_format((float)($apartments_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Primarily owned</th>
      <td>'.$primary_ownership_no['sum'].'</td>
      <td>'.number_format((float)($primary_ownership_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Secondarily owned</th>
      <td>'.$secondary_ownership_no['sum'].'</td>
      <td>'.number_format((float)($secondary_ownership_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">TV</th>
      <td>'.$tv_no['sum'].'</td>
      <td>'.number_format((float)($tv_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">WiFi</th>
      <td>'.$wifi_no['sum'].'</td>
      <td>'.number_format((float)($wifi_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Air Con.</th>
      <td>'.$ac_no['sum'].'</td>
      <td>'.number_format((float)($ac_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Private Gym</th>
      <td>'.$gym_no['sum'].'</td>
      <td>'.number_format((float)($gym_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Wheelchair Accessible</th>
      <td>'.$wheelchair_no['sum'].'</td>
      <td>'.number_format((float)($wheelchair_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Pets Allowed</th>
      <td>'.$pets_no['sum'].'</td>
      <td>'.number_format((float)($pets_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Kids Friendly</th>
      <td>'.$kids_no['sum'].'</td>
      <td>'.number_format((float)($kids_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Parking</th>
      <td>'.$parking_no['sum'].'</td>
      <td>'.number_format((float)($parking_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Security Guard</th>
      <td>'.$security_no['sum'].'</td>
      <td>'.number_format((float)($security_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Private Garden</th>
      <td>'.$garden_no['sum'].'</td>
      <td>'.number_format((float)($garden_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Home Workers</th>
      <td>'.$workers_no['sum'].'</td>
      <td>'.number_format((float)($workers_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
    <tr>
      <th scope="row">Smokers Allowed</th>
      <td>'.$smokers_no['sum'].'</td>
      <td>'.number_format((float)($smokers_no['sum']/$homes_no['sum']) * 100,2,'.','').'%</td>
    </tr>
</table>
<p>In the past month, there has been a total of <b>'.$total_home_availabilities['sum'].' home availabilities</b> Below is the <b>home availability distribution in the previous 4 weeks</b>.</p>
<ol>
    <b><li>Week 1: '.$week_1_availabilities['sum'].' homes were newly available</li>
    <li>Week 2: '.$week_2_availabilities['sum'].' homes were newly available</li>
    <li>Week 3: '.$week_3_availabilities['sum'].' homes were newly available</li>
    <li>Week 4: '.$week_4_availabilities['sum'].' homes were newly available</li></b>
</ol>
<p>The past month has seen<b> '.$month_requests_no['sum'].' new home exchange requests</b> and a total of <b>'.$exchanges_month['sum'].' home exchanges</b>. Below is a <b>weekly distribution of home requests</b> and a <b>weekly distribution of home exchanges</b> made on through the platform respectively.</p>
<p>Some exchanges made are from home availabilities sloted in previous months.</p>
<h4>Exchange Requests</h4>
<table border="1" cellspacing="1" cellpadding="4" align="center">
    <tr>
        <th><b>Week</b></th>
        <th><b>Number of requests</b></th>
    </tr>
     <tr>
        <td>Week 1</td>
        <td>'.$week_1_requests['sum'].'</td>
    </tr>
    <tr>
        <td>Week 2</td>
        <td>'.$week_2_requests['sum'].'</td>
    </tr>
    <tr>
        <td>Week 3</td>
        <td>'.$week_3_requests['sum'].'</td>
    </tr>
    <tr>
        <td>Week 4</td>
        <td>'.$week_4_requests['sum'].'</td>
    </tr>
</table>

<h4>Home Exchanges</h4>
<table border="1" cellspacing="1" cellpadding="4" align="center">
    <tr>
        <th><b>Week</b></th>
        <th><b>Number of exchanges</b></th>
    </tr>
     <tr>
        <td>Week 1</td>
        <td>'.$week_1_exchanges['sum'].'</td>
    </tr>
    <tr>
        <td>Week 2</td>
        <td>'.$week_2_exchanges['sum'].'</td>
    </tr>
    <tr>
        <td>Week 3</td>
        <td>'.$week_3_exchanges['sum'].'</td>
    </tr>
    <tr>
        <td>Week 4</td>
        <td>'.$week_4_exchanges['sum'].'</td>
    </tr>
</table>
<p>The <b>top 5 demanded counties</b> in terms of requests in the past 6 months are as follows:</p>
<table border="1" cellspacing="1" cellpadding="4" align="center">
    <tr>
        <th><b>County</b></th>
        <th><b>Number of requests</b></th>
    </tr>
    ';
    $totalDemand = 0;
    foreach($demandedCounties as $row){
     $html .= '<tr>
        <td>'.$row['county'].'</td>
        <td>'.$row['sum'].'</td>
    </tr>';
    $totalDemand += $row['sum'];
    }
    $totalsum = $requests_no['sum'];
    $other = $totalsum - $totalDemand;
$html .= '
     <tr>
        <td>Others</td>
        <td>'.$other.'</td>
    </tr>
</table>
';

$pdf->writeHTML($html, true, false, true, false, '');
// reset pointer to the last page
$pdf->lastPage();
//Close and output PDF document
ob_end_clean();
$pdf->Output('Report.pdf', 'I');
